jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
  
spring:
  datasource:
    password: soni12345
    url: jdbc:mysql://localhost:3306/SpringSecurity
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false

  
   
server:
  port: 9091
  
#  error:
#    whitelabel:
#      enabled: false
  